// <auto-generated />
using System;
using Flashy.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flashy.Data.Context
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flashy")
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flashy.Data.Models.DeckFlashCard", b =>
                {
                    b.Property<Guid>("DeckId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeckId");

                    b.Property<Guid>("FlashCardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FlashCardId");

                    b.Property<Guid>("FlashCardsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeckId", "FlashCardId")
                        .HasName("PK_DecksFlashCards");

                    b.HasIndex("FlashCardId");

                    b.HasIndex("FlashCardsId");

                    b.ToTable("DecksFlashCards", "flashy");
                });

            modelBuilder.Entity("Flashy.Data.Models.UserDeck", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeckId");

                    b.HasKey("UserId", "DeckId")
                        .HasName("PK_UsersDecks");

                    b.HasIndex("DeckId");

                    b.ToTable("UsersDecks", "flashy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedById");

                    b.Property<string>("Description")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("NormalizedName");

                    b.HasKey("Id")
                        .HasName("PK_Decks");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Decks_CreatedAt");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("IX_Decks_CreatedById");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_Decks_NormalizedName");

                    b.ToTable("Decks", "flashy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.FlashCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Back")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Back");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedById");

                    b.Property<string>("Front")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Front");

                    b.Property<string>("Hint")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Hint");

                    b.Property<string>("NormalizedBack")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("NormalizedBack");

                    b.Property<string>("NormalizedFront")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("NormalizedFront");

                    b.HasKey("Id")
                        .HasName("PK_FlashCards");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FlashCards_CreatedAt");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("IX_FlashCards_CreatedBy");

                    b.HasIndex("NormalizedBack")
                        .IsUnique()
                        .HasDatabaseName("IX_FlashCards_NormalizedBack");

                    b.HasIndex("NormalizedFront")
                        .IsUnique()
                        .HasDatabaseName("IX_FlashCards_NormalizedFront");

                    b.ToTable("FlashCards", "flashy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NormalizedName");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_NormalizedName");

                    b.ToTable("Roles", "flashy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ClaimType");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ClaimValue");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.HasKey("Id")
                        .HasName("PK_RoleClaims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_RoleClaims_RoleId");

                    b.ToTable("RoleClaims", "flashy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ClaimType");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ClaimValue");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("PK_UserClaims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserClaims_UserId");

                    b.ToTable("UserClaims", "flashy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("LoginProvider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ProviderKey");

                    b.Property<string>("NormalizedProviderDisplayName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("NormalizedProviderDisplayName");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ProviderDisplayName");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("PK_UserLogins");

                    b.HasIndex("NormalizedProviderDisplayName")
                        .HasDatabaseName("IX_UserLogins_NormalizedProviderDisplayName");

                    b.HasIndex("ProviderDisplayName")
                        .HasDatabaseName("IX_UserLogins_ProviderDisplayName");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserLogins_UserId");

                    b.ToTable("UserLogins", "flashy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "flashy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("LoginProvider")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("LoginProvider");

                    b.Property<string>("Name")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("PK_UserTokens");

                    b.ToTable("UserTokens", "flashy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("LastName");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("NormalizedEmail");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NormalizedUserName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UserName");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_NormalizedUserName");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UserName");

                    b.ToTable("Users", "flashy");
                });

            modelBuilder.Entity("Flashy.Data.Models.DeckFlashCard", b =>
                {
                    b.HasOne("Flashy.Shared.Models.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("FK_DecksFlashCards_Decks");

                    b.HasOne("Flashy.Shared.Models.FlashCard", "FlashCard")
                        .WithMany()
                        .HasForeignKey("FlashCardId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("FK_DecksFlashCards_FlashCards");

                    b.HasOne("Flashy.Shared.Models.FlashCard", null)
                        .WithMany()
                        .HasForeignKey("FlashCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("FlashCard");
                });

            modelBuilder.Entity("Flashy.Data.Models.UserDeck", b =>
                {
                    b.HasOne("Flashy.Shared.Models.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UsersDecks_Decks");

                    b.HasOne("Flashy.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UsersDecks_Users");

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Deck", b =>
                {
                    b.HasOne("Flashy.Shared.Models.User", "CreatedBy")
                        .WithMany("CreatedDecks")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Decks_CreatedBy");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.FlashCard", b =>
                {
                    b.HasOne("Flashy.Shared.Models.User", "CreatedBy")
                        .WithMany("CreatedFlashCards")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlashCards_CreatedBy");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.RoleClaim", b =>
                {
                    b.HasOne("Flashy.Shared.Models.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.UserClaim", b =>
                {
                    b.HasOne("Flashy.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.UserLogin", b =>
                {
                    b.HasOne("Flashy.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.UserRole", b =>
                {
                    b.HasOne("Flashy.Shared.Models.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flashy.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flashy.Shared.Models.Identity.UserToken", b =>
                {
                    b.HasOne("Flashy.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flashy.Shared.Models.User", b =>
                {
                    b.Navigation("CreatedDecks");

                    b.Navigation("CreatedFlashCards");
                });
#pragma warning restore 612, 618
        }
    }
}
